name: bdk_flutter
description: A Flutter library for the Bitcoin Development Kit(bdk) (https://bitcoindevkit.org/)
version: 0.32.0
homepage: https://github.com/LtbLightning/bdk-flutter

environment:
  sdk: "^3.10.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: "^2.11.1"
  ffi: ^2.1.4
  freezed_annotation: ^3.1.0
  mockito: ^5.6.1
  collection: ^1.19.0
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^20.1.1
  freezed: ^3.2.3
  build_runner: ^2.10.4
  lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
